---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_main_config_file: "../config/{{ survey_service }}_config.yml"

  vars_files:
  - "{{ service_main_config_file }}"

  tasks:
  - name: Creating Virtual Networks 
    azure_rm_virtualnetwork:
      resource_group: "{{ az_resourcegroup_name }}"
      name: "{{ item.name }}"
      address_prefixes: "{{ item.address_prefixes }}"
    with_items: "{{ az_virtual_networks }}"
