---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_main_config_file: "../config/{{ survey_service }}_config.yml"

  vars_files:
  - "{{ service_main_config_file }}"

  tasks:
  - name: Deleting the VM {{ survey_vm_delete1 }}
    azure_rm_virtualmachine:
      resource_group: "{{ az_resourcegroup_name }}"
      name: "{{ survey_vm_delete1 }}"
      vm_size: "{{ vm_flavor }}"
      network_interfaces: "{{ az_resourcegroup_name }}_{{ survey_vm_delete1 }}_NIC"
      tags:
        srv: "{{ service_name }}"
      state: absent
    when: survey_vm_delete1 == survey_vm_delete2

  - name: Deleting Security Group
    azure_rm_securitygroup:
      resource_group: "{{ az_resourcegroup_name }}"
      name: "{{ az_resourcegroup_name }}_{{ survey_vm_delete1 }}_SecurityGroupSSH_HTTP"
      state: absent
