---
- hosts: "srv_{{ survey_service }}"
  gather_facts: no
  vars:
    service_main_config_file: "config/{{ survey_service }}_config.yml"

  vars_files:
  - "{{ service_main_config_file }}"

  tasks:
  - name: Checking service {{ survey_service }}
    shell: curl http://localhost
